# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [2]:
df = df.rename(columns={"Customer Lifetime Value": "cust_life_value", "Monthly Premium Auto": "mont_prem_val", "Number of Open Complaints": "num_open_comp"})
df = df.rename(columns={"ST": "state", "Customer": "customer", "GENDER": "gender", "Education": "education", "Policy Type": "policy_type", "Vehicle Class": "vehicle_class", "Total Claim Amount": "tot_claim_amount"})
df.head()

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

# Gender column

In [3]:
print(df['gender'].unique())

[nan 'F' 'M' 'Femal' 'Male' 'female']

In [4]:
df["gender"] = df["gender"].str.strip().str.lower()
print(df['gender'].unique())

[nan 'f' 'm' 'femal' 'male' 'female']

In [5]:
df["gender"] = df["gender"].replace({"m": "Male", "f": "female", "femal": "female", "Male": "male"})

In [6]:
print(df['gender'].unique())

[nan 'female' 'Male' 'male']

# State abbreviations

In [7]:
print(df['state'].unique())

['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'Cali' 'AZ' 'WA'
 nan]

In [8]:
df["state"] = df["state"].replace({"Cali": "California", "AZ": "Arizona", "WA": "Washington"})

In [9]:
print(df['state'].unique())

['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' nan]

# "Bachelors" could be replaced by "Bachelor"*

In [10]:
print(df['education'].unique())

['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor'
 nan]

In [11]:
df["education"] = df["education"].replace({"Bachelors": "Bachelor"})

In [12]:
print(df['education'].unique())

['Master' 'Bachelor' 'High School or Below' 'College' 'Doctor' nan]

# Customer Lifetime Value, delete the `%` character

In [13]:
print(df['cust_life_value'].unique())

[nan '697953.59%' '1288743.17%' ... '2031499.76%' '323912.47%'
 '899704.02%']

In [14]:
df["cust_life_value"] = df["cust_life_value"].replace({"%": ""}, regex=True)

In [15]:
print(df['cust_life_value'].unique())

[nan '697953.59' '1288743.17' ... '2031499.76' '323912.47' '899704.02']

# In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [16]:
print(df['vehicle_class'].unique())

['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car' nan]

In [17]:
df["vehicle_class"] = df["vehicle_class"].replace({"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"})

In [18]:
print(df['vehicle_class'].unique())

['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury' nan]

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

# Customer lifetime value should be numeric

In [19]:
print(df['cust_life_value'].head())

0           NaN
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: cust_life_value, dtype: object

In [20]:
df["cust_life_value"] = pd.to_numeric(df["cust_life_value"], errors="coerce")

In [21]:
print(df['cust_life_value'].head())

0           NaN
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: cust_life_value, dtype: float64

# *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [22]:
print(df['num_open_comp'].unique())

['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]

In [23]:
df['num_open_comp'].str.split("/")

0       [1, 0, 00]
1       [1, 0, 00]
2       [1, 0, 00]
3       [1, 0, 00]
4       [1, 0, 00]
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: num_open_comp, Length: 4008, dtype: object

In [24]:
df["num_open_comp"] = df["num_open_comp"].str.split("/").str[1]

In [25]:
df["num_open_comp"] = pd.to_numeric(df["num_open_comp"], errors="coerce")

In [26]:
print(df['num_open_comp'].unique())

[ 0.  2.  1.  3.  5.  4. nan]

df.head()

In [27]:
df['num_open_comp'].dtype

dtype('float64')

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

# Identify any columns with null or missing values. Identify how many null values each column has. You can use the isnull() function in pandas to find columns with null values.

In [28]:
df.isnull()

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4003,True,True,True,True,True,True,True,True,True,True,True
4004,True,True,True,True,True,True,True,True,True,True,True
4005,True,True,True,True,True,True,True,True,True,True,True
4006,True,True,True,True,True,True,True,True,True,True,True
4007,True,True,True,True,True,True,True,True,True,True,True

In [29]:
df.head()

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,female,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,female,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,Male,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,Male,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

# customer - Decided to convert null to not loose the important transaction data link to this costumers. 
replaced by Unknown.

In [36]:
df["customer"] = df["customer"].fillna("Unknown")

# state - The same decision, to keep the transactions linked to this one.

In [38]:
df["state"] = df["state"].fillna("Unknown")

# gender - The same decision, to keep the transactions

In [40]:
df["gender"] = df["gender"].fillna("Unknown")

# education - same decision

In [42]:
df["education"] = df["education"].fillna("Unknown")

# cust_life_value - Decided to fill missing tihe the median values. IT was a high ammout of values to discard

In [49]:
df["cust_life_value"] = df["cust_life_value"].fillna(df["cust_life_value"].median())

In [ ]:
# Income I decided to apply median, because of the outliers gathering by mean.

In [57]:
df["Income"] = df["Income"].fillna(df["Income"].median())

# Monthly Premium Auto applied the same median, because of the possible outliers from the mean.

In [59]:
df["mont_prem_val"] = df["mont_prem_val"].fillna(df["mont_prem_val"].median())

# Number of Open Complaints - Decided to use mode, because its a short list of diferent results.

In [70]:
df["num_open_comp"].unique()

array([0., 2., 1., 3., 5., 4.])

In [68]:
mode_value = df["num_open_comp"].mode()[0]
df["num_open_comp"] = df["num_open_comp"].fillna(mode_value)

# Policy type - Decided to change null to the most frequent value of the used car, in thuis data column.

In [71]:
df["policy_type"].unique()

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

In [72]:
df["policy_type"].value_counts()

policy_type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [73]:
mode_value = df["policy_type"].mode()[0]
df["policy_type"] = df["policy_type"].fillna(mode_value)

# vehicle class - same as previous - change null to the most frequent value

In [75]:
df["vehicle_class"].value_counts()

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Luxury            91
Name: count, dtype: int64

In [76]:
mode_value = df["vehicle_class"].mode()[0]
df["vehicle_class"] = df["vehicle_class"].fillna(mode_value)

# tot_claim_amount - Decided to apply the same median, because of the possible outliers from the mean.

In [78]:
df["tot_claim_amount"].value_counts()

tot_claim_amount
321.600000    19
331.200000    15
312.000000    14
350.400000    14
316.800000    12
              ..
171.325856     1
249.085887     1
30.874869      1
361.455219     1
42.096415      1
Name: count, Length: 761, dtype: int64

In [79]:
df["tot_claim_amount"] = df["tot_claim_amount"].fillna(df["tot_claim_amount"].median())

In [80]:
df.isnull()

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4003,False,False,False,False,False,False,False,False,False,False,False
4004,False,False,False,False,False,False,False,False,False,False,False
4005,False,False,False,False,False,False,False,False,False,False,False
4006,False,False,False,False,False,False,False,False,False,False,False
4007,False,False,False,False,False,False,False,False,False,False,False

# After formatting data types, as a last step, convert all the numeric variables to integers.

In [81]:
df.select_dtypes(include=["number"]).columns

Index(['cust_life_value', 'Income', 'mont_prem_val', 'num_open_comp',
       'tot_claim_amount'],
      dtype='object')

In [85]:
df.dtypes

customer             object
state                object
gender               object
education            object
cust_life_value     float64
Income              float64
mont_prem_val       float64
num_open_comp       float64
policy_type          object
vehicle_class        object
tot_claim_amount    float64
dtype: object

In [88]:
df[df.select_dtypes(include=["number"]).columns] = (df.select_dtypes(include=["number"]).round().astype(int))

In [89]:
df.dtypes

customer            object
state               object
gender              object
education           object
cust_life_value      int64
Income               int64
mont_prem_val        int64
num_open_comp        int64
policy_type         object
vehicle_class       object
tot_claim_amount     int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

# Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

In [90]:
df.duplicated().sum()

np.int64(2936)

In [91]:
df.duplicated().any()

np.True_

In [93]:
df.duplicated(subset=['customer']).sum()

np.int64(2936)

In [95]:
df.state.duplicated().any()

np.True_

In [96]:
df.drop_duplicates(inplace=True)

In [97]:
df.duplicated().sum()

np.int64(0)

In [99]:
df.duplicated(subset=['customer']).sum()

np.int64(0)

In [92]:
df.head()

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,RB50392,Washington,Unknown,Master,588174,0,1000,0,Personal Auto,Four-Door Car,3
1,QZ44356,Arizona,female,Bachelor,697954,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,female,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,Male,Bachelor,764586,0,106,0,Corporate Auto,SUV,530
4,GA49547,Washington,Male,High School or Below,536308,36357,68,0,Personal Auto,Four-Door Car,17

# after dropping duplicates, reset the index to ensure consistency

In [100]:
df = df.reset_index(drop=True)

In [101]:
df.index

RangeIndex(start=0, stop=1072, step=1)

In [102]:
df.head()

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,RB50392,Washington,Unknown,Master,588174,0,1000,0,Personal Auto,Four-Door Car,3
1,QZ44356,Arizona,female,Bachelor,697954,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,female,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,Male,Bachelor,764586,0,106,0,Corporate Auto,SUV,530
4,GA49547,Washington,Male,High School or Below,536308,36357,68,0,Personal Auto,Four-Door Car,17

# Save the cleaned dataset to a new CSV file.

In [103]:
df.to_csv("filename_without_nas.csv")

In [104]:
df

,customer,state,gender,education,cust_life_value,Income,mont_prem_val,num_open_comp,policy_type,vehicle_class,tot_claim_amount
0,RB50392,Washington,Unknown,Master,588174,0,1000,0,Personal Auto,Four-Door Car,3
1,QZ44356,Arizona,female,Bachelor,697954,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,female,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,Male,Bachelor,764586,0,106,0,Corporate Auto,SUV,530
4,GA49547,Washington,Male,High School or Below,536308,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
1067,VJ51327,California,female,High School or Below,2031500,63209,102,2,Personal Auto,SUV,207
1068,GS98873,Arizona,female,Bachelor,323912,16061,88,0,Personal Auto,Four-Door Car,634
1069,CW49887,California,female,Master,462680,79487,114,0,Special Auto,SUV,547
1070,MY31220,California,female,College,899704,54230,112,0,Personal Auto,Two-Door Car,538
1071,Unknown,Unknown,Unknown,Unknown,588174,36234,83,0,Personal Auto,Four-Door Car,355

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [33]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [34]:
# Your code here